### ISSUE TITLE
Verbose logging options for Docker

### ISSUE THREAD

**Issue by WurdNerd** [Madpeterz/SecondBot#10]
**Is your feature request related to a problem? Please describe.**
A local logfile for the Docker instance to be used for Troubleshooting

**Describe the solution you'd like**
We run into issues sometimes where it's unclear if we are doing something wrong or if something is wrong with the bot, it would be nice to have a local logfile where the bot could spit errors, exceptionss, status updates that aren't even posted into the interface chat. Things like "Creating channel for <user> because they sent me an IM" "Opening IM from <user>: <content>" 

**Describe alternatives you've considered**
Logging levels would also be nice just for the interface channel however it would be less spammy if it was a logfile instead

**Comment by Madpeterz** [comment]
I have added the following flags

Log2File_Enable {True|False}  "Enable writing to logs to files [Logs are sent to the Logs folder]"

Log2File_Level {int} [1 by default] "This setting is also used for the console display"
-1: Nothing
0: Status only
1: +Info
2: +Crititcal
3: +Warnings
4: +Debug


this is just a first pass at the log writer and should be improved with levels later on.


if this first pass does not cover the functions you want under debug please let me know and list
actions you want to be tracked with debug.

**Comment by Madpeterz** [comment]
https://github.com/Madpeterz/SecondBot/commit/089db101966ff6aa9bdfeffd2158c7a697e0fe62
