### ISSUE TITLE
Request: Make bots logout on logoff command as well as logout command

### ISSUE THREAD

**Issue by hellershanks** [Madpeterz/SecondBot#11]
plzkthnxinfo~

**Comment by Madpeterz** [comment]
solved with 
https://github.com/Madpeterz/SecondBot/commit/5b4b94352c71b6bbb6d0546742b3baeaa0ef5baf
+
https://github.com/Madpeterz/SecondBot/commit/3ba59c90df2e39a5dff9fd2eaee31d0a532a5c7e
