### ISSUE TITLE
Two way group chat communication via full mode in a remote discord server

### ISSUE THREAD

**Issue by hellershanks** [Madpeterz/SecondBot#12]
Running bot in full fat discord and allowing two way group chat communication in a separate discord server.

**Comment by Madpeterz** [comment]
https://github.com/Madpeterz/SecondBot/commit/3aae9aa96433ffada648a71a6a5e381db6f829e7

Adding 2 relays
one for discord to the group and one for the group to discord will do this
note: This system is in testing and will replace the old relay to UUID system thats currently in the bot.
