### ISSUE TITLE
Second life response going to a "SecondLife channel in Discord

### ISSUE THREAD

**Issue by kahfluie** [Madpeterz/SecondBot#17]
**Describe the bug**
When the user is not online, the SL message is going to a SecondLife Channel (IM box) in Discord.

**To Reproduce**
1. Send a message to someone not online
2. see the response and its location

**Expected behavior**
The response is sent to the appropriate channel i.e. if I send madpeter a message and he is not online, it goes to the discord channel (IM box) create title Madpeter

**Screenshots**
You already saw it happen live... 

**Hardware (please complete the following information):**
Discord and Docker

**Additional context**
N/A

**Comment by Madpeterz** [comment]
Im going to have to close this, secondlife does not let me know who the message was for that failed and its extra work to track that, so im going to just hide the secondlife messages for now
