### ISSUE TITLE
Estate: Get ban list

### ISSUE THREAD

**Issue by KanikaBreed** [Madpeterz/SecondBot#22]
Add option to get estate ban list.  Give name and UUID

**Comment by Madpeterz** [comment]
added support for this via HTTP, needs testing.
core will get access to this command when the commands finish moving over to HTTP.

**Comment by Madpeterz** [comment]
https://wiki.magicmadpeter.xyz/files/HTTPestatebanlist.html

**Comment by Madpeterz** [comment]
closing please feel free to create / reopen if issue continues
