### ISSUE TITLE
Ability to do action when people enter in a selected parcel 

### ISSUE THREAD

**Issue by ronmg** [Madpeterz/SecondBot#37]
hello , can you add a function to ask bot to do things when people enter in a selected parcel 

thx

**Comment by Madpeterz** [comment]
This request is under testing now via
https://github.com/Madpeterz/SecondBot/wiki/OnEvents
with the tracker enabled and set to Event
and using the GuestEntersArea on event.

**Comment by Madpeterz** [comment]
This should now be working, please report any issues
