### ISSUE TITLE
HowTo Configure

### ISSUE THREAD

**Issue by AlexStephenLytton** [Madpeterz/SecondBot#53]
Maybe i've missed something but unfortunately i don't get any hint how to configure SecondBot or how to configure docker to get it working properly. There's also no documentation for any of the commands i've found. 

Is it possible to get a link to a documentation or a guide how to get second bot up and running?

**Comment by Madpeterz** [comment]
https://github.com/Madpeterz/SecondBot/wiki/Setting-up-(Docker-with-Portainer)

https://github.com/Madpeterz/SecondBot/wiki/Commands

**Comment by Madpeterz** [comment]
Closing this issue for now, if you still need help please reopen this issue.
