### ISSUE TITLE
Ability to utilize local storage to create a log of visitors

### ISSUE THREAD

**Issue by hellershanks** [Madpeterz/SecondBot#56]
I would like the bots to be able to log to local file who visits the sim, at what time, and the duration of their stay categorized by date

**Comment by Madpeterz** [comment]
I can create a system that logs

time, event, uuid

and appends that to a file.

but to get the duration you will have to review the file to find the arrival event and depart event.

**Comment by Madpeterz** [comment]
using the events system you would now push that to a service and do the work there its a bit out of scope for the bot.
