### ISSUE TITLE
missing compile instruction

### ISSUE THREAD

**Issue by freddii** [Madpeterz/SecondBot#67]
I can not find a compile instruction for SecondBot.

**Comment by Madpeterz** [comment]
open the code in visual studio, select release then build
then select BetterSecondbot project and select publish.

if your using docker then use the premade images.

**Comment by freddii** [comment]
I tried to build BetterSecondbot but file is only 87.5 KiB big and not working:
cd $HOME
wget https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
rm packages-microsoft-prod.deb

sudo apt-get update; \
  sudo apt-get install -y apt-transport-https && \
  sudo apt-get update && \
  sudo apt-get install -y dotnet-sdk-6.0
  
sudo apt install git-core

git clone https://github.com/Madpeterz/SecondBot

cd SecondBot/
dotnet restore "BetterSecondbot/BetterSecondbot.csproj"

cd BetterSecondbot

mkdir app
cd app
mkdir build
cd ..

dotnet build "BetterSecondbot.csproj" -c Release -o ./app/build
