### ISSUE TITLE
http_enable=true crash bot

### ISSUE THREAD

**Issue by freddii** [Madpeterz/SecondBot#69]
**Describe the bug**
Bot shuts down with error message when Http_Enable is set to true:
System.UnauthorizedAccessException: Access to the path '/scoped_tokens.json' is denied.

**To Reproduce**
1. running BetterSecondbot-linux-666510b.zip on linux
2. See error

**Expected behavior**
 no crash with Http_Enable set to true

**Hardware (please complete the following information):**
 - OS: linux
 - Version [666510b
 - Running in docker: No

**Comment by Madpeterz** [comment]
Confirmed - the IO system was not picking up the current working directory and just writing to the top of the disk.

**Comment by Madpeterz** [comment]
fixed as of https://github.com/Madpeterz/SecondBot/commit/b78df43cc585c7d2dae74407f9c47bbe46af9613
