### ISSUE TITLE
put all commands into Commands.md in the github wiki

### ISSUE THREAD

**Issue by freddii** [Madpeterz/SecondBot#70]
It would be nice to have all Commands in Commands.md
Markdown is easy to read and EDIT from every texteditor.
[Commands.md](https://github.com/Madpeterz/SecondBot/files/7773220/Commands.md)

**Comment by Madpeterz** [comment]
sure the wiki is auto created I could have it create a md file to me to import

**Comment by Madpeterz** [comment]
done 

https://github.com/Madpeterz/SecondBot/blob/main/commands.md

the html wiki maker also makes the markdown ^+^

**Comment by freddii** [comment]
👍
