### ISSUE TITLE
SetParcelSale Command - Allow L$0 Direct Sales

### ISSUE THREAD

**Issue by Ruimuuv** [Madpeterz/SecondBot#72]
**Is your feature request related to a problem? Please describe.**
I am attempting to use the bot to automatically clear and resell parcels in my estate when a tenant goes overdue. This process involves using estate manager permissions to reclaim the parcel which sets the parcel owner to the region owner. I then transfer the parcel to be owned by my group before listing it for sale. To do this within SL's permission system requires the bot to sell the parcel to itself (land goes from being owned by the region owner to being owned by the bot) and then deed the parcel to the group. At this point the bot may tweak parcel settings as necessary before finally listing the parcel for sale.

The problem lies within the parcel transfer steps. Currently I get an error `{"reply": "Invaild amount","status": false}` when trying to sell the parcel from the region owner directly to the bot with a L$0 price. This is a departure from SL viewer behavior which allows L$0 direct sales, but disallows L$0 sales to "anyone".

**Describe the solution you'd like**
The command `parcel/SetParcelSale` should allow a L$0 price when a parcel is set for sale directly to another avatar (i.e. the "avatar" argument for the command is not "none").

**Describe alternatives you've considered**
The only other option I've considered is to set the price of a parcel sale to L$1 when transferring directly. This is not ideal as it requires continuously ensuring that the bot account has a wallet balance to use for these transactions either by paying L$ to the bot manually or by using LSL's debit permissions to automate the transfer.

**Comment by Madpeterz** [comment]
can you please update your docker and try again with 0 and an assigned avatar
https://github.com/Madpeterz/SecondBot/commit/3dc3499a8c52d1698ff933965fc9d474491950dd

should have fixed the issue

**Comment by Ruimuuv** [comment]
After updating the SetParcelSale command works as expected. However ParcelBuy also needs a similar change; the bot cannot currently buy the parcel if it is set for sale directly to the bot account for L$0.

**Comment by Ruimuuv** [comment]
Buying is now working too, thanks!

**Comment by Madpeterz** [comment]
ok im going to go ahead and close this, if you find any more bug / want something added open a new issue ^+^
