### ISSUE TITLE
Feature request: Controlling a bot with IMs

### ISSUE THREAD

**Issue by lemmy04** [Madpeterz/SecondBot#73]
**Is your feature request related to a problem? Please describe.**
I would like to be able to control a bot with chat commands from the "bot master" account.

**Describe the solution you'd like**
I would like to send the bot the same commands that are used from the Web UI, but in an IM.
These commands would only be executed if they come from one of the accounts that are set as bot master in the configuration.
For example, "sit <uuid>" to sit on the object with that uuid, or "Say hello world"

**Comment by lemmy04** [comment]
I might be blind: how do I control a bot with IM? If I IM my bot and send it this: "Say|||0~#~hello" nothing happens.

**Comment by Madpeterz** [comment]
when you setup your bot did you put your avatar's UUID as the master?

**Comment by lemmy04** [comment]
d'uh. I put the avatar names in - let me try with UUIDs instead.
If the username doesn't work that page should be updated... XD

**Comment by lemmy04** [comment]
Putting the UUID in didnt help either. Sending an IM with exactly this: "Say|||0~#~hello" and nothing happens.

**Comment by Madpeterz** [comment]
If your still stuck feel free to add me in secondlife: Madpeter Zond

**Comment by lemmy04** [comment]
I'm just not getting it. I'm running the bot inside in docker, controlled from portainer, with this compose file: https://gist.github.com/lemmy04/b30d7e1794c49dbcd4b1e78c246865aa (sensitive values, i.e. passwords and logins, have been removed).
I send the bot an IM from the account that is listed as Security_MasterUsername with the text Say|||0~#~Test and it does not work. then, I stop the stack in portainer, start it again, without making any changes, and try again: it works. I restart the stack again, try it again, it doesn't work.

**Comment by Madpeterz** [comment]
you can also reach me on discord: Madpeter#9732

**Comment by Madpeterz** [comment]
Marking this issue as closed for now feel free to contact me if you are stuck.

**Comment by lemmy04** [comment]
I believe I'm getting closer to finding what's going on here: the avatar that I'm having trouble with usually wears a "stepford implant", an attachment that redirects chat via RLV to do its own thing with anything the avatar says, similar to chat translation devices or RLV gags - as soon as i take that off before logging in that account with SecondBot, IM commands seem to work.
