### ISSUE TITLE
Feature request: RLV support

### ISSUE THREAD

**Issue by lemmy04** [Madpeterz/SecondBot#74]
**Is your feature request related to a problem? Please describe.**
I would like to have better control over a bot from **within** SL.

**Describe the solution you'd like**
If the bot software had support for RLV I could just slap a collar on a bot and use that to control the bot.

**Additional context**
RLV support could be adapted from Radegast which **has** RLV and is also written in c#...

**Comment by Madpeterz** [comment]
RLV is now supported in the events based update
