### ISSUE TITLE
Give Folder  Inventory error

### ISSUE THREAD

**Issue by longhorns709** [Madpeterz/SecondBot#88]
**Describe the bug**
When sending the command with the correct UUID for give folder the command responds with a incorrect uuid.  

**To Reproduce**
Send the command with a correct uuid 
 parseCmd("SendFolder",["5fce3da5-6acd-42ef-a39a-5b4b30c1fbe8+",(string)llDetectedKey(0)],"0");

**Expected behavior**
It is so post to give you the folder with everything in it.

**Screenshots**
https://i.imgur.com/ckwnV1x.png

**Comment by Madpeterz** [comment]
fixed in the events recode
