### ISSUE TITLE
Bot Relogs ever 15-45 min

### ISSUE THREAD

**Issue by longhorns709** [Madpeterz/SecondBot#89]
**Describe the bug**
The bot is using HTTPS and for some reason the bot will reboot and after coming back online it will not respond to commands reliably and has to be reset to work again.

**To Reproduce**
Have bot connected to StreamAdmin7 and it will have the issue also.

**Expected behavior**
Should just stay on and not reboot

**Screenshots**
 Just logs... 
[08:12] THEbot_01 is offline.
[08:12] THEbot_01 is online.
[08:27] THEbot_01 is offline.
[08:27] THEbot_01 is online.
[09:11] THEbot_01 is offline.
[09:12] THEbot_01 is online.
[09:56] THEbot_01 is offline.
[09:56] THEbot_01 is online.

**Comment by Scotspaul** [comment]
has this issue been fixed yet as mine is also logging in and out

**Comment by Madpeterz** [comment]
Fixed with the events update (now live), if you are using streamadmin you will need to wait for a update before switching
