### ISSUE TITLE
Bot ability to map all parcels on a region.

### ISSUE THREAD

**Issue by shadoskill** [Madpeterz/SecondBot#97]
**Describe the solution you'd like**
I want the bot to have the ability to map an entire region of all of its parcels into a nice JSON object.
Should have the main key be the parcel UUID, and the value be a object of parcel owner UUID, total square meters, vector of each 16m squared chunk.

**Describe alternatives you've considered**
I tried it with LSL and it ran out of memory.

**Comment by Madpeterz** [comment]
rejected out of scope

**Comment by Madpeterz** [comment]
fixed with
https://github.com/Madpeterz/SecondBot/commit/efe66731d563fecc4502219fab280fe338ba11de
